# Generated by Django 2.2.6 on 2019-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='Worker', max_length=64, null=True)),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
    ]
