# Generated by Django 2.2.6 on 2019-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, default='Company', max_length=32, null=True),
        ),
    ]
