# Generated by Django 2.2.6 on 2019-11-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.IntegerField(default=0, verbose_name='salary from'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.IntegerField(default=0, verbose_name='salary to'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='url',
            field=models.URLField(default='https://hh.ru', verbose_name='URL'),
        ),
    ]
