# Generated by Django 2.2.6 on 2019-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20191107_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, default='Company', max_length=128, null=True),
        ),
    ]
