# Generated by Django 2.2.6 on 2019-11-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20191107_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.CharField(default='0', max_length=10, verbose_name='salary from'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.CharField(default='0', max_length=10, verbose_name='salary to'),
        ),
    ]
