# Generated by Django 2.2.6 on 2019-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20191107_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
