# Generated by Django 2.2.6 on 2019-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_vacancy_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='salary from'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='salary to'),
        ),
    ]
