# Generated by Django 2.2.6 on 2019-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20191110_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='salary from'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='salary to'),
        ),
    ]
