version: '3'

services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_invert_key_word_index:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_cache_response:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_word_cache:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_query_text:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_couple_word:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_synonym_word:
    image: "redis:alpine"
    ports:
      - "6379"
  redis_invert_text_index:
    image: "redis:alpine"
    ports:
      - "6379"
  web:
    build: .
    command: bash -c "python /code/manage.py makemigrations --noinput && python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - redis_invert_key_word_index
      - redis_cache_response
      - redis_word_cache
      - redis_query_text
      - redis_couple_word
      - redis_synonym_word
      - redis_invert_text_index
    restart: on-failure
    links: 
      - db
  celery:
    build: .
    command: celery -A aggregator worker -l info -E
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    command: celery -A aggregator beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
