"""
Django settings for aggregator project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rlttn@n6y4bo!d-!w5v_@^wprb_o6)nm9=ex!$ipg10wx#gguq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.43.36', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storage',
    'word_parse',
    'jinja2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aggregator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'aggregator.jinja2.environment',
        },
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


WSGI_APPLICATION = 'aggregator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432
    }
}
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Redis settings

INVERT_KEY_WORD_INDEX_REDIS_HOST = 'redis_invert_key_word_index'
INVERT_KEY_WORD_INDEX_REDIS_PORT = 6379

RESPONSE_CACHE_REDIS_HOST = 'redis_cache_response'
RESPONSE_CACHE_REDIS_PORT = 6379

WORD_CACHE_REDIS_HOST = 'redis_word_cache'
WORD_CACHE_REDIS_PORT = 6379

QUERY_TEXT_CACHE_REDIS_HOST = 'redis_query_text'
QUERY_TEXT_CACHE_REDIS_PORT = 6379

COUPLE_WORD_REDIS_HOST = 'redis_couple_word'
COUPLE_WORD_REDIS_PORT = 6379

SYNONYM_WORD_REDIS_HOST = 'redis_synonym_word'
SYNONYM_WORD_REDIS_PORT = 6379

INVERT_TEXT_INDEX_REDIS_HOST = 'redis_invert_text_index'
INVERT_TEXT_INDEX_REDIS_PORT = 6379


# celery settings

from celery.schedules import crontab
from storage.schedules import beat_schedule

CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IMPORTS = ('storage.tasks')
CELERY_BEAT_SCHEDULE = beat_schedule
CELERY_TIMEZONE = 'Europe/Moscow'


